// Generated by https://quicktype.io

export interface Invoices {
  no: string;
  dueDate: string;
  total: number;
  status: string;
  from: From;
  to: From;
  createdAt: string;
  updatedAt: string;
}

export interface From {
  name: string;
  email: string;
  company: string;
  address: string;
  city: string;
  state: string;
  country: string;
  zip: number;
  about: string;
}
